site_name: Weatherforecast C# Documentation
nav:
  - Home: index.md
  - WeatherForecast: weatherforecast-csharp/README.md
repo_url: https://github.com/ricket-son/tap-sample
plugins:
  - techdocs-core
