apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=tanzu-java-web-app
    backstage.io/techdocs-ref: dir:/
  links:
    - url: https://tanzu-java-web-app.tap-test-dev.tap.dieunkrauts.de
      title: Tanzu Java Web App
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: default-team
